# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66dabe95436faf7f1f24a72bc0fc02980ae28b913d31422b653b2af21c3704db31ddb52e68b391013998de908eadc592fdd1d1ef7dba0673fef563de1b27b57

test:
  secret_key_base: 0760cbad66ff261e03452c0c8bcc1595caa79d32d9691fb413f9a28b3fd5f7f3d39cadc9409335492057ece720e94a55f35a8b85ce570e77329508eb180f780d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
